-- Vanuatu Tours & Attractions Seed Data
-- This file contains seed data for tours across Vanuatu

-- Clear existing data (optional - comment out if you want to append)
-- TRUNCATE TABLE tour_reviews CASCADE;
-- TRUNCATE TABLE tour_bookings CASCADE;
-- TRUNCATE TABLE tours CASCADE;

-- ============================================
-- ADVENTURE TOURS
-- ============================================

INSERT INTO tours (
  id, name, description, short_description, location, island, category,
  price_adult, price_child, duration_hours, difficulty_level, max_group_size, min_age,
  image_url, rating, review_count, highlights, includes, excludes, what_to_bring,
  available_days, start_times, provider_name, is_active
) VALUES
(
  '10000000-0001-0000-0000-000000000001',
  'Mount Yasur Volcano Night Tour',
  'Experience the raw power of nature at Mount Yasur, one of the world''s most accessible active volcanoes. Watch spectacular eruptions illuminate the night sky as molten lava shoots into the air. This UNESCO World Heritage site on Tanna Island offers an unforgettable adventure that few places on Earth can match. Our experienced guides ensure your safety while providing fascinating insights into the volcano''s geology and cultural significance to local communities.',
  'Witness spectacular volcanic eruptions at the world''s most accessible active volcano',
  'Tanna Island',
  'Tanna',
  'adventure',
  15000,
  10000,
  4.0,
  'moderate',
  15,
  8,
  NULL,
  4.9,
  142,
  ARRAY['Watch live volcanic eruptions from the crater rim', 'Spectacular night-time lava displays', 'Expert volcano guides with safety equipment', 'Learn about local Tannese culture and beliefs', 'Stunning sunset views over the ash plains'],
  ARRAY['Hotel pickup and drop-off', 'Licensed volcano guide', 'Safety helmets and masks', 'Light refreshments', 'Viewing permit fees'],
  ARRAY['Flights to Tanna', 'Meals', 'Travel insurance'],
  ARRAY['Sturdy closed-toe shoes', 'Warm jacket', 'Camera', 'Torch/flashlight', 'Long pants'],
  ARRAY['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
  ARRAY['15:00'],
  'Tanna Volcano Tours',
  true
),
(
  '10000000-0001-0000-0000-000000000002',
  'Millennium Cave Adventure',
  'Embark on the ultimate Vanuatu adventure through the spectacular Millennium Cave. This challenging full-day expedition takes you through lush jungle, bamboo forests, river crossings, and into one of the South Pacific''s largest cave systems. Wade through underground rivers, marvel at towering cathedral-like chambers, and experience the thrill of canyoneering through pristine wilderness. This is adventure tourism at its finest.',
  'Trek through jungle and explore massive cave systems with river crossings',
  'Luganville, Santo',
  'Espiritu Santo',
  'adventure',
  12500,
  9000,
  8.0,
  'challenging',
  12,
  10,
  NULL,
  4.8,
  98,
  ARRAY['Trek through pristine rainforest', 'Wade through underground rivers inside the cave', 'Experience the massive cathedral chamber', 'Bamboo rafting on the river', 'Swim in crystal-clear freshwater pools'],
  ARRAY['Expert local guides', 'Safety equipment (helmets, life jackets)', 'Lunch and refreshments', 'Transport from Luganville', 'Walking poles'],
  ARRAY['Accommodation', 'Personal travel insurance', 'Flights to Santo'],
  ARRAY['Water shoes or old sneakers', 'Quick-dry clothes', 'Waterproof bag for camera', 'Change of clothes', 'Sunscreen', 'Insect repellent'],
  ARRAY['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday'],
  ARRAY['07:00'],
  'Santo Adventures',
  true
),
(
  '10000000-0001-0000-0000-000000000003',
  'Zip Line Canopy Tour',
  'Soar through the treetops of Vanuatu''s pristine rainforest on this exhilarating zip line adventure. Fly across multiple platforms connected by high-speed cables, enjoying bird''s-eye views of the jungle canopy below. Learn about the local ecosystem from your guides as you traverse suspension bridges and viewing platforms. Perfect for thrill-seekers of all ages!',
  'Fly through the jungle canopy on exhilarating zip lines',
  'Port Vila, Efate',
  'Efate',
  'adventure',
  8500,
  6500,
  3.0,
  'moderate',
  10,
  6,
  NULL,
  4.7,
  187,
  ARRAY['6 thrilling zip lines through the canopy', 'Suspension bridge walks', 'Panoramic jungle views', 'Professional safety equipment', 'Learn about rainforest ecology'],
  ARRAY['All safety equipment and harnesses', 'Expert guides and safety briefing', 'Light refreshments', 'Transport from Port Vila hotels'],
  ARRAY['Lunch', 'Photos (available for purchase)'],
  ARRAY['Closed-toe shoes', 'Comfortable clothes', 'Camera with strap', 'Sunscreen'],
  ARRAY['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
  ARRAY['09:00', '13:00'],
  'Vanuatu Eco Tours',
  true
);

-- ============================================
-- CULTURAL TOURS
-- ============================================

INSERT INTO tours (
  id, name, description, short_description, location, island, category,
  price_adult, price_child, duration_hours, difficulty_level, max_group_size, min_age,
  image_url, rating, review_count, highlights, includes, excludes, what_to_bring,
  available_days, start_times, provider_name, is_active
) VALUES
(
  '10000000-0002-0000-0000-000000000001',
  'Traditional Kastom Village Experience',
  'Step back in time and experience authentic Melanesian culture in a traditional kastom village. Witness ancient customs and ceremonies that have been preserved for generations. Watch traditional dancing, learn about local medicinal plants, see how kava is prepared, and participate in a welcoming ceremony. This immersive experience provides genuine insight into ni-Vanuatu life and traditions.',
  'Immerse yourself in authentic Melanesian culture and traditions',
  'Ekasup Village, Efate',
  'Efate',
  'cultural',
  6500,
  4000,
  3.5,
  'easy',
  20,
  0,
  NULL,
  4.9,
  215,
  ARRAY['Traditional welcome ceremony', 'Kastom dancing and music performances', 'Demonstration of fire-making and cooking', 'Kava preparation ceremony', 'Traditional craft demonstrations', 'Meet local village elders'],
  ARRAY['Village entrance fee', 'Cultural performances', 'Traditional refreshments', 'Local guide', 'Transport from Port Vila'],
  ARRAY['Meals', 'Souvenirs', 'Kava (available for purchase)'],
  ARRAY['Modest clothing covering shoulders and knees', 'Camera', 'Small cash for souvenirs'],
  ARRAY['tuesday', 'thursday', 'saturday'],
  ARRAY['09:30', '14:00'],
  'Ekasup Cultural Tours',
  true
),
(
  '10000000-0002-0000-0000-000000000002',
  'Land Diving Ceremony (Naghol)',
  'Witness the original bungee jump - the legendary land diving ceremony of Pentecost Island. Men dive headfirst from towers up to 30 meters high with only vines attached to their ankles. This ancient ritual marks the yam harvest and demonstrates courage and faith. A truly once-in-a-lifetime cultural experience that has been practiced for centuries.',
  'Witness the legendary land diving ceremony - the original bungee jump',
  'Pentecost Island',
  'Pentecost',
  'cultural',
  35000,
  25000,
  6.0,
  'easy',
  30,
  0,
  NULL,
  5.0,
  67,
  ARRAY['Watch death-defying dives from 30-meter towers', 'Experience authentic kastom ceremonies', 'Meet the brave land divers', 'Traditional singing and dancing', 'Visit local villages', 'Photography opportunities'],
  ARRAY['Charter flight to Pentecost', 'Ceremony viewing fees', 'Local guides', 'Traditional lunch', 'Ground transfers'],
  ARRAY['Accommodation', 'Personal items'],
  ARRAY['Comfortable walking shoes', 'Sun protection', 'Camera', 'Rain jacket (weather dependent)'],
  ARRAY['saturday'],
  ARRAY['07:00'],
  'Pentecost Cultural Tours',
  true
),
(
  '10000000-0002-0000-0000-000000000003',
  'Chief Roi Mata Heritage Site Tour',
  'Explore Vanuatu''s only UNESCO World Heritage Site - the domain of Chief Roi Mata. Visit the ancient ceremonial grounds, the sacred burial site on Artok Island, and learn about this legendary chief who united warring tribes 400 years ago. A fascinating journey through history with stories of peace, leadership, and cultural preservation.',
  'Visit Vanuatu''s UNESCO World Heritage Site and learn ancient history',
  'Mangaas, Efate',
  'Efate',
  'cultural',
  9500,
  6000,
  5.0,
  'easy',
  12,
  0,
  NULL,
  4.8,
  89,
  ARRAY['Visit UNESCO World Heritage Site', 'Boat trip to Artok burial island', 'Learn the legend of Chief Roi Mata', 'Traditional welcome ceremony', 'Visit Fele''s Cave', 'Traditional lunch included'],
  ARRAY['UNESCO certified guide', 'Boat transfers to Artok Island', 'Traditional Melanesian lunch', 'All entrance fees', 'Hotel pickup (Port Vila)'],
  ARRAY['Souvenirs', 'Additional drinks'],
  ARRAY['Comfortable walking shoes', 'Sunscreen', 'Hat', 'Camera', 'Insect repellent'],
  ARRAY['monday', 'wednesday', 'friday'],
  ARRAY['08:30'],
  'Roi Mata Heritage Tours',
  true
);

-- ============================================
-- NATURE TOURS
-- ============================================

INSERT INTO tours (
  id, name, description, short_description, location, island, category,
  price_adult, price_child, duration_hours, difficulty_level, max_group_size, min_age,
  image_url, rating, review_count, highlights, includes, excludes, what_to_bring,
  available_days, start_times, provider_name, is_active
) VALUES
(
  '10000000-0003-0000-0000-000000000001',
  'Blue Lagoon & Nanda Blue Hole',
  'Discover the magical blue holes of Espiritu Santo, where crystal-clear freshwater springs create stunning azure pools in the jungle. Swim in the famous Nanda Blue Hole, surrounded by lush tropical vegetation, then visit the beautiful Blue Lagoon for more swimming and a delicious local lunch. These natural wonders are among the most photographed spots in Vanuatu.',
  'Swim in stunning crystal-clear blue holes surrounded by jungle',
  'Luganville, Santo',
  'Espiritu Santo',
  'nature',
  7500,
  5000,
  5.0,
  'easy',
  12,
  0,
  NULL,
  4.9,
  234,
  ARRAY['Swim in the famous Nanda Blue Hole', 'Visit the stunning Blue Lagoon', 'Rope swing into crystal-clear water', 'Tropical lunch included', 'Photo opportunities galore'],
  ARRAY['Transport from Luganville', 'Entrance fees', 'Local lunch', 'Drinking water', 'Knowledgeable local guide'],
  ARRAY['Accommodation', 'Personal items', 'Souvenirs'],
  ARRAY['Swimsuit', 'Towel', 'Waterproof camera', 'Sunscreen', 'Insect repellent'],
  ARRAY['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
  ARRAY['09:00', '13:00'],
  'Santo Blue Hole Tours',
  true
),
(
  '10000000-0003-0000-0000-000000000002',
  'Mele Cascades Waterfall Hike',
  'Trek through lush tropical rainforest to the spectacular Mele Cascades, a series of stunning waterfalls with natural swimming pools. Climb alongside the falls using ropes and ladders, swim in refreshing pools at each level, and enjoy the beauty of Vanuatu''s pristine wilderness. Just 20 minutes from Port Vila, this is the perfect half-day adventure.',
  'Hike to beautiful cascading waterfalls with natural swimming pools',
  'Mele Village, Efate',
  'Efate',
  'nature',
  5500,
  3500,
  3.0,
  'moderate',
  15,
  5,
  NULL,
  4.7,
  312,
  ARRAY['Multiple waterfall levels to explore', 'Natural swimming pools', 'Rope and ladder climbing sections', 'Lush rainforest setting', 'Cool off in fresh mountain water'],
  ARRAY['Park entrance fee', 'Local guide', 'Drinking water', 'Transport from Port Vila'],
  ARRAY['Meals', 'Towel rental'],
  ARRAY['Water shoes or old sneakers', 'Swimsuit', 'Towel', 'Waterproof bag for valuables', 'Camera'],
  ARRAY['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
  ARRAY['08:00', '13:00'],
  'Mele Eco Tours',
  true
),
(
  '10000000-0003-0000-0000-000000000003',
  'Hideaway Island Nature Walk',
  'Explore the tiny but beautiful Hideaway Island, just minutes from Port Vila. Walk the nature trail circling the island, snorkel the famous Underwater Post Office, and relax on pristine beaches. This small island paradise is perfect for a half-day escape with snorkeling, swimming, and natural beauty.',
  'Explore a tiny paradise island with snorkeling and beaches',
  'Hideaway Island, Efate',
  'Efate',
  'nature',
  4500,
  3000,
  4.0,
  'easy',
  20,
  0,
  NULL,
  4.6,
  178,
  ARRAY['Visit the Underwater Post Office', 'Snorkel with tropical fish', 'Circle the island nature walk', 'Relax on white sand beaches', 'Short ferry ride experience'],
  ARRAY['Return ferry transfers', 'Island entrance fee', 'Snorkeling equipment', 'Beach chairs and umbrella use'],
  ARRAY['Meals and drinks', 'Underwater postcards'],
  ARRAY['Swimsuit', 'Towel', 'Sunscreen', 'Camera', 'Cash for food/drinks'],
  ARRAY['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
  ARRAY['09:00', '11:00', '14:00'],
  'Hideaway Island Resort',
  true
);

-- ============================================
-- WATER SPORTS TOURS
-- ============================================

INSERT INTO tours (
  id, name, description, short_description, location, island, category,
  price_adult, price_child, duration_hours, difficulty_level, max_group_size, min_age,
  image_url, rating, review_count, highlights, includes, excludes, what_to_bring,
  available_days, start_times, provider_name, is_active
) VALUES
(
  '10000000-0004-0000-0000-000000000001',
  'SS President Coolidge Wreck Dive',
  'Dive one of the world''s best and most accessible wreck dives - the SS President Coolidge. This massive WWII troopship lies in shallow waters off Santo, making it perfect for divers of all levels. Explore the massive hull, discover "The Lady" statue, jeeps, helmets, and countless artifacts from this fascinating piece of history.',
  'Explore one of the world''s best WWII shipwreck dives',
  'Million Dollar Point, Santo',
  'Espiritu Santo',
  'water_sports',
  18000,
  NULL,
  4.0,
  'moderate',
  8,
  12,
  NULL,
  4.9,
  156,
  ARRAY['Dive the massive WWII troopship', 'See "The Lady" and "The Helmets"', 'Explore cargo holds with jeeps and supplies', 'Professional dive guides', 'Multiple dive sites available'],
  ARRAY['Two dives', 'Full dive equipment', 'Dive guide', 'Tanks and weights', 'Refreshments between dives'],
  ARRAY['Dive certification required', 'Lunch', 'Underwater camera rental'],
  ARRAY['Dive certification card', 'Log book', 'Underwater camera', 'Reef-safe sunscreen'],
  ARRAY['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday'],
  ARRAY['08:00', '13:00'],
  'Santo Island Dive',
  true
),
(
  '10000000-0004-0000-0000-000000000002',
  'Kayak & Snorkel Adventure',
  'Paddle through pristine waters in a kayak before snorkeling colorful coral reefs. This perfect combination tour lets you explore Vanuatu''s coastline from above and below the water. Suitable for beginners, with calm waters and easy-to-use sit-on-top kayaks. Guides will show you the best snorkeling spots with amazing coral and tropical fish.',
  'Paddle and snorkel through beautiful coral reefs',
  'Port Vila Harbor',
  'Efate',
  'water_sports',
  6500,
  4500,
  3.0,
  'easy',
  8,
  6,
  NULL,
  4.7,
  143,
  ARRAY['Kayak through calm harbor waters', 'Snorkel coral reefs', 'See tropical fish and marine life', 'Perfect for beginners', 'Beautiful coastal scenery'],
  ARRAY['Kayak and paddle', 'Snorkeling equipment', 'Life jacket', 'Waterproof bag', 'Guide and safety briefing', 'Light refreshments'],
  ARRAY['Transport', 'Underwater camera'],
  ARRAY['Swimsuit', 'Towel', 'Reef-safe sunscreen', 'Hat', 'Water'],
  ARRAY['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday'],
  ARRAY['09:00', '14:00'],
  'Vanuatu Sea Kayaks',
  true
),
(
  '10000000-0004-0000-0000-000000000003',
  'Sunset Sailing Cruise',
  'Sail into the sunset aboard a beautiful yacht in Port Vila Harbor. Enjoy the golden hour with champagne, canapes, and stunning views of the islands. Watch the sun dip below the horizon as the sky turns incredible colors. The perfect romantic experience or special celebration.',
  'Cruise into the sunset with champagne and stunning views',
  'Port Vila Harbor',
  'Efate',
  'water_sports',
  9000,
  NULL,
  2.5,
  'easy',
  12,
  18,
  NULL,
  4.8,
  98,
  ARRAY['Sail on a beautiful yacht', 'Champagne and canapes included', 'Stunning sunset views', 'Photo opportunities', 'Romantic atmosphere'],
  ARRAY['Champagne', 'Canapes and snacks', 'Professional skipper', 'Yacht cruise'],
  ARRAY['Meals', 'Additional alcoholic drinks'],
  ARRAY['Light jacket', 'Camera', 'Sunglasses'],
  ARRAY['monday', 'wednesday', 'friday', 'saturday'],
  ARRAY['17:00'],
  'Sail Vanuatu',
  true
);

-- ============================================
-- ISLAND HOPPING TOURS
-- ============================================

INSERT INTO tours (
  id, name, description, short_description, location, island, category,
  price_adult, price_child, duration_hours, difficulty_level, max_group_size, min_age,
  image_url, rating, review_count, highlights, includes, excludes, what_to_bring,
  available_days, start_times, provider_name, is_active
) VALUES
(
  '10000000-0005-0000-0000-000000000001',
  'Mystery Island Day Trip',
  'Escape to the uninhabited paradise of Mystery Island (Inyeug) for a day of pure tropical bliss. This tiny island offers pristine beaches, crystal-clear snorkeling, and peaceful relaxation. Enjoy a beach barbecue, swim in warm turquoise waters, and explore this picture-perfect island. See why cruise ships make this their top Vanuatu destination.',
  'Day trip to an uninhabited paradise island with beaches and snorkeling',
  'Mystery Island, Tanna',
  'Tanna',
  'island_hopping',
  22000,
  15000,
  8.0,
  'easy',
  20,
  0,
  NULL,
  4.8,
  134,
  ARRAY['Visit uninhabited tropical paradise', 'Pristine white sand beaches', 'Amazing snorkeling and swimming', 'Beach barbecue lunch', 'Meet local village craftspeople'],
  ARRAY['Return transfers', 'Beach BBQ lunch', 'Snorkeling equipment', 'Beach chairs and umbrellas', 'Local guide'],
  ARRAY['Flights to Tanna', 'Alcoholic drinks', 'Souvenirs'],
  ARRAY['Swimsuit', 'Towel', 'Sunscreen', 'Hat', 'Cash for souvenirs', 'Camera'],
  ARRAY['tuesday', 'thursday', 'saturday'],
  ARRAY['07:30'],
  'Tanna Island Tours',
  true
),
(
  '10000000-0005-0000-0000-000000000002',
  'Epi Island Whale Watching',
  'Journey to Epi Island for an unforgettable encounter with pilot whales. These friendly cetaceans regularly swim close to shore in the shallow bays, offering incredible opportunities to swim alongside them. Combined with visits to local villages and natural attractions, this is a unique Vanuatu experience.',
  'Swim with friendly pilot whales in their natural habitat',
  'Lamen Bay, Epi',
  'Epi',
  'island_hopping',
  28000,
  20000,
  10.0,
  'moderate',
  10,
  8,
  NULL,
  4.9,
  45,
  ARRAY['Swim with pilot whales', 'Small group experience', 'Visit local villages', 'Traditional lunch', 'Scenic flight over islands'],
  ARRAY['Return flights to Epi', 'Local transfers', 'Traditional lunch', 'Snorkeling equipment', 'Expert whale guide'],
  ARRAY['Accommodation', 'Personal insurance'],
  ARRAY['Swimsuit', 'Waterproof camera', 'Sunscreen', 'Change of clothes'],
  ARRAY['monday', 'wednesday', 'friday'],
  ARRAY['06:30'],
  'Epi Whale Adventures',
  true
);

-- ============================================
-- WILDLIFE TOURS
-- ============================================

INSERT INTO tours (
  id, name, description, short_description, location, island, category,
  price_adult, price_child, duration_hours, difficulty_level, max_group_size, min_age,
  image_url, rating, review_count, highlights, includes, excludes, what_to_bring,
  available_days, start_times, provider_name, is_active
) VALUES
(
  '10000000-0006-0000-0000-000000000001',
  'Turtle Sanctuary & Snorkeling Tour',
  'Visit a turtle conservation sanctuary and snorkel with sea turtles in their natural habitat. Learn about the conservation efforts protecting these amazing creatures, then enter the water to swim alongside them. An educational and unforgettable experience for wildlife lovers of all ages.',
  'Meet sea turtles at a sanctuary and snorkel with them',
  'Tranquility Island, Efate',
  'Efate',
  'wildlife',
  7500,
  5000,
  4.0,
  'easy',
  12,
  0,
  NULL,
  4.8,
  201,
  ARRAY['Meet rescued sea turtles', 'Snorkel with wild turtles', 'Learn about conservation', 'Feed and interact with turtles', 'Beautiful island setting'],
  ARRAY['Boat transfers', 'Sanctuary entrance', 'Snorkeling equipment', 'Turtle feeding', 'Guide'],
  ARRAY['Meals', 'Photos'],
  ARRAY['Swimsuit', 'Towel', 'Reef-safe sunscreen', 'Underwater camera'],
  ARRAY['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday', 'sunday'],
  ARRAY['09:00', '13:30'],
  'Tranquility Island Eco Tours',
  true
),
(
  '10000000-0006-0000-0000-000000000002',
  'Bat Cave & Bird Watching',
  'Explore ancient limestone caves home to thousands of flying foxes (fruit bats) and discover Vanuatu''s diverse birdlife. Watch the spectacular evening exodus as bats leave for feeding, and spot endemic bird species in the surrounding forest. Perfect for nature photographers and wildlife enthusiasts.',
  'Watch thousands of flying foxes and spot exotic birds',
  'Devil''s Point, Efate',
  'Efate',
  'wildlife',
  5500,
  3500,
  3.5,
  'easy',
  10,
  5,
  NULL,
  4.6,
  89,
  ARRAY['See thousands of flying foxes', 'Spot endemic bird species', 'Cave exploration', 'Nature walk through forest', 'Spectacular bat exodus at dusk'],
  ARRAY['Transport from Port Vila', 'Expert naturalist guide', 'Cave entrance', 'Binoculars use', 'Light refreshments'],
  ARRAY['Meals', 'Camera equipment'],
  ARRAY['Binoculars', 'Camera', 'Comfortable shoes', 'Long pants', 'Insect repellent'],
  ARRAY['monday', 'wednesday', 'friday', 'saturday'],
  ARRAY['15:30'],
  'Vanuatu Wildlife Tours',
  true
);

-- ============================================
-- CULINARY TOURS
-- ============================================

INSERT INTO tours (
  id, name, description, short_description, location, island, category,
  price_adult, price_child, duration_hours, difficulty_level, max_group_size, min_age,
  image_url, rating, review_count, highlights, includes, excludes, what_to_bring,
  available_days, start_times, provider_name, is_active
) VALUES
(
  '10000000-0007-0000-0000-000000000001',
  'Melanesian Cooking Class',
  'Learn to prepare traditional Melanesian cuisine in this hands-on cooking class. Visit the local market to select fresh ingredients, then create authentic dishes like lap lap, tuluk, and simboro under the guidance of a local chef. Finish by enjoying the feast you''ve prepared!',
  'Cook and taste authentic Melanesian cuisine',
  'Port Vila, Efate',
  'Efate',
  'culinary',
  8500,
  6000,
  4.0,
  'easy',
  8,
  8,
  NULL,
  4.9,
  76,
  ARRAY['Visit local market with chef', 'Learn traditional cooking techniques', 'Prepare 4 authentic dishes', 'Enjoy the meal you create', 'Take home recipe cards'],
  ARRAY['All ingredients', 'Cooking instruction', 'Full meal', 'Recipe cards', 'Apron to keep', 'Market tour'],
  ARRAY['Drinks', 'Transport'],
  ARRAY['Comfortable clothes', 'Closed-toe shoes', 'Appetite!'],
  ARRAY['tuesday', 'thursday', 'saturday'],
  ARRAY['09:00'],
  'Taste of Vanuatu',
  true
),
(
  '10000000-0007-0000-0000-000000000002',
  'Kava Ceremony & Local Dinner',
  'Experience Vanuatu''s national drink in an authentic setting. Join locals at a nakamal (kava bar) for a traditional kava ceremony, learning about this culturally significant drink''s preparation and customs. Followed by a delicious local dinner featuring island cuisine.',
  'Authentic kava ceremony followed by traditional dinner',
  'Port Vila, Efate',
  'Efate',
  'culinary',
  5500,
  NULL,
  3.0,
  'easy',
  10,
  18,
  NULL,
  4.7,
  123,
  ARRAY['Traditional kava ceremony', 'Learn kava preparation', 'Multiple shells of kava', 'Local dinner included', 'Cultural insights from guides'],
  ARRAY['Kava (multiple shells)', 'Traditional dinner', 'Local guide', 'Transport from hotels'],
  ARRAY['Alcoholic drinks', 'Additional food'],
  ARRAY['Open mind', 'Modest clothing', 'Empty stomach (kava works best!)'],
  ARRAY['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday'],
  ARRAY['17:30'],
  'Nakamal Tours',
  true
);

-- ============================================
-- HISTORICAL TOURS
-- ============================================

INSERT INTO tours (
  id, name, description, short_description, location, island, category,
  price_adult, price_child, duration_hours, difficulty_level, max_group_size, min_age,
  image_url, rating, review_count, highlights, includes, excludes, what_to_bring,
  available_days, start_times, provider_name, is_active
) VALUES
(
  '10000000-0008-0000-0000-000000000001',
  'WWII Heritage Trail',
  'Explore Vanuatu''s fascinating World War II history on this comprehensive tour of military sites on Santo. Visit Million Dollar Point where US forces dumped equipment into the sea, see the rusting remains of aircraft and vehicles, and learn about the island''s strategic importance during the Pacific War.',
  'Discover WWII history including Million Dollar Point',
  'Luganville, Santo',
  'Espiritu Santo',
  'historical',
  7000,
  4500,
  4.0,
  'easy',
  15,
  0,
  NULL,
  4.7,
  112,
  ARRAY['Visit Million Dollar Point', 'See aircraft and vehicle remains', 'Learn about WWII Pacific history', 'Visit US military base locations', 'Snorkel over dumped equipment'],
  ARRAY['Transport', 'Knowledgeable guide', 'Entrance fees', 'Snorkeling equipment', 'Refreshments'],
  ARRAY['Meals', 'Underwater camera'],
  ARRAY['Swimsuit', 'Towel', 'Sunscreen', 'Camera', 'Comfortable shoes'],
  ARRAY['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday'],
  ARRAY['08:30', '13:30'],
  'Santo War Tours',
  true
),
(
  '10000000-0008-0000-0000-000000000002',
  'Port Vila Walking History Tour',
  'Discover the rich colonial and modern history of Vanuatu''s capital on this walking tour. Visit historic buildings, learn about the Anglo-French Condominium era, see independence landmarks, and understand how this unique nation came to be. Perfect for history buffs and those wanting to understand Vanuatu better.',
  'Walking tour of Port Vila''s historic sites and landmarks',
  'Port Vila, Efate',
  'Efate',
  'historical',
  4500,
  2500,
  2.5,
  'easy',
  12,
  0,
  NULL,
  4.5,
  87,
  ARRAY['Visit colonial-era buildings', 'See independence landmarks', 'Learn Condominium history', 'Visit the central market', 'Local guide insights'],
  ARRAY['Expert local guide', 'Bottled water', 'Market visit'],
  ARRAY['Meals', 'Entrance fees to museums', 'Transport'],
  ARRAY['Comfortable walking shoes', 'Sunscreen', 'Hat', 'Camera', 'Water bottle'],
  ARRAY['monday', 'tuesday', 'wednesday', 'thursday', 'friday', 'saturday'],
  ARRAY['09:00', '15:00'],
  'Vila Walking Tours',
  true
);

-- Summary: 18 tours covering all 8 categories across multiple islands
