// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ljervgzsovamehnlztxf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxqZXJ2Z3pzb3ZhbWVobmx6dHhmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjMwMTY2NTcsImV4cCI6MjA3ODU5MjY1N30.Oo2H5Kc8SUREjjT9DqiCP1fiWpTnZ7rHjTACTuqWHxU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});