project_id = "ljervgzsovamehnlztxf"

[functions.hello-world]
verify_jwt = false

[functions.create-ride-payment]
verify_jwt = true

[functions.process-driver-payout]
verify_jwt = true

[functions.check-payment-status]
verify_jwt = false

[functions.send-driver-notification]
verify_jwt = false

[functions.send-auth-email]
verify_jwt = false

[functions.create-marketplace-payment]
verify_jwt = true

[functions.sync-marketplace-payment]
verify_jwt = true

[functions.create-shop-delivery-route]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false
